SELECT CRCC.CAR_ID,
        CRCC.CAR_TYPE, 
        FLOOR(CRCC.DAILY_FEE * 30 * ((100 - CRCDP.DISCOUNT_RATE) / 100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS CRCC
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS CRCDP
ON  CRCC.CAR_TYPE = CRCDP.CAR_TYPE
WHERE CRCDP.CAR_TYPE IN ('세단', 'SUV') 
AND CRCC.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30'
)
AND CRCDP.DURATION_TYPE = '30일 이상'
HAVING FEE >= 500000 AND FEE <= 2000000
ORDER BY FEE DESC, CRCDP.CAR_TYPE ASC, CRCC.CAR_ID DESC
