# [방법 1. JOIN + NULL 체크]
SELECT AOUT.ANIMAL_ID, AOUT.NAME
FROM ANIMAL_INS AS AIN
RIGHT JOIN ANIMAL_OUTS AS AOUT
ON AIN.ANIMAL_ID = AOUT.ANIMAL_ID
WHERE AIN.ANIMAL_ID IS NULL;

# [방법 2. 서브쿼리]
SELECT AOUT.ANIMAL_ID, AOUT.NAME
FROM ANIMAL_OUTS AS AOUT
WHERE AOUT.ANIMAL_ID NOT IN (
    SELECT AIN.ANIMAL_ID FROM ANIMAL_INS AS AIN
)
