SELECT 
    YEAR(SALE.SALES_DATE) AS YEAR,
    MONTH(SALE.SALES_DATE) AS MONTH,
    COUNT(DISTINCT USERI.USER_ID) AS PURCHASED_USERS,
    
    ROUND(COUNT(DISTINCT USERI.USER_ID) / (
        SELECT COUNT(DISTINCT USER_ID)
        FROM USER_INFO 
        WHERE JOINED BETWEEN '2021-01-01' AND'2021-12-31'
    ), 1) AS PUCHASED_RATIO
    
FROM USER_INFO AS USERI
JOIN ONLINE_SALE AS SALE
ON USERI.USER_ID = SALE.USER_ID
WHERE USERI.JOINED BETWEEN '2021-01-01' AND'2021-12-31'
GROUP BY
    YEAR(SALE.SALES_DATE),
    MONTH(SALE.SALES_DATE)