SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, FP.PRICE * FOSUM.TOTAL_AMOUNT AS TOTAL_SALES
FROM FOOD_PRODUCT AS FP
JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL_AMOUNT
    FROM FOOD_ORDER AS FO
    WHERE DATE_FORMAT(FO.PRODUCE_DATE, '%Y-%m') = '2022-05'
    GROUP BY PRODUCT_ID
) AS FOSUM
ON FP.PRODUCT_ID = FOSUM.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID ASC