SELECT FH.FLAVOR
FROM FIRST_HALF AS FH
JOIN (
    SELECT SUM(TOTAL_ORDER) AS JULTOTAL, FLAVOR
    FROM JULY
    GROUP BY FLAVOR
) AS JUL
ON FH.FLAVOR = JUL.FLAVOR
ORDER BY FH.TOTAL_ORDER + JUL.JULTOTAL DESC
LIMIT 3;