SELECT DISTINCT NUM AS ConsecutiveNums 
FROM
(SELECT 
    NUM,
    LAG(NUM, 1) OVER (ORDER BY ID) AS NEXT_NUM_1,
    LAG(NUM, 2) OVER (ORDER BY ID) AS NEXT_NUM_2
FROM LOGS) AS TEMP
WHERE NUM = NEXT_NUM_1 AND NUM = NEXT_NUM_2
