SELECT DEPARTMENT, EMPLOYEE, SALARY
FROM
    (SELECT
        D.NAME AS DEPARTMENT,
        E.NAME AS EMPLOYEE,
        E.SALARY AS SALARY,
        DENSE_RANK() OVER (
            PARTITION BY E.DEPARTMENTID
            ORDER BY E.SALARY DESC
        ) AS RANKNUM

    FROM EMPLOYEE AS E
    JOIN DEPARTMENT AS D
    ON E.DEPARTMENTID = D.ID) AS TMP
WHERE RANKNUM <= 3
