SELECT ROUND(SUM(TIV_2016), 2) AS TIV_2016
FROM
(SELECT
    TIV_2016,
    COUNT(*) OVER (PARTITION BY TIV_2015) AS COUNTTIV,
    COUNT(*) OVER (PARTITION BY LAT, LON) AS COUNTLATLON
FROM INSURANCE) AS TMP
WHERE COUNTTIV > 1 AND COUNTLATLON = 1
