(SELECT U.NAME AS RESULTS
FROM USERS AS U
JOIN MOVIERATING AS RATING
ON U.USER_ID = RATING.USER_ID
GROUP BY U.USER_ID
ORDER BY COUNT(*) DESC, U.NAME ASC
LIMIT 1)

UNION ALL

(SELECT MOVIE.TITLE AS RESULTS
FROM MOVIES AS MOVIE
JOIN MOVIERATING AS RATING
ON MOVIE.MOVIE_ID = RATING.MOVIE_ID
-- WHERE YEAR(RATING.CREATED_AT) = 2020 AND MONTH(RATING.CREATED_AT) = 2

WHERE RATING.CREATED_AT >= '2020-02-01' AND RATING.CREATED_AT < '2020-03-01'
GROUP BY MOVIE.MOVIE_ID
ORDER BY AVG(RATING.RATING) DESC, MOVIE.TITLE ASC
LIMIT 1)
